/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TierCategory = IDL.Record({
  'tier' : IDL.Text,
  'category' : IDL.Text,
});
export const PlayerRanking = IDL.Record({
  'region' : IDL.Text,
  'title' : IDL.Text,
  'username' : IDL.Text,
  'badges' : IDL.Vec(TierCategory),
  'uuid' : IDL.Text,
  'rankPosition' : IDL.Nat,
  'points' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RankingGroup = IDL.Text;
export const RawRankingData = IDL.Record({
  'axe' : IDL.Vec(PlayerRanking),
  'smp' : IDL.Vec(PlayerRanking),
  'uhc' : IDL.Vec(PlayerRanking),
  'diamondSmpNethopSpear' : IDL.Vec(PlayerRanking),
  'mace' : IDL.Vec(PlayerRanking),
  'nethop' : IDL.Vec(PlayerRanking),
  'sword' : IDL.Vec(PlayerRanking),
  'vanilla' : IDL.Vec(PlayerRanking),
  'overall' : IDL.Vec(PlayerRanking),
  'spearMace' : IDL.Vec(PlayerRanking),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func([PlayerRanking], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(PlayerRanking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMaxRankedPoints' : IDL.Func([], [IDL.Nat], ['query']),
  'getPlayer' : IDL.Func([IDL.Text], [IDL.Opt(PlayerRanking)], ['query']),
  'getPlayerRankByRanking' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PlayerRanking)],
      ['query'],
    ),
  'getRankingCategories' : IDL.Func([], [RankingGroup], ['query']),
  'getRankingCategory' : IDL.Func([], [RankingGroup], ['query']),
  'getRankingEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getRawRankingData' : IDL.Func([], [RawRankingData], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPlayersByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PlayerRanking)],
      ['query'],
    ),
  'switchRankingCategory' : IDL.Func([RankingGroup], [RankingGroup], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TierCategory = IDL.Record({ 'tier' : IDL.Text, 'category' : IDL.Text });
  const PlayerRanking = IDL.Record({
    'region' : IDL.Text,
    'title' : IDL.Text,
    'username' : IDL.Text,
    'badges' : IDL.Vec(TierCategory),
    'uuid' : IDL.Text,
    'rankPosition' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RankingGroup = IDL.Text;
  const RawRankingData = IDL.Record({
    'axe' : IDL.Vec(PlayerRanking),
    'smp' : IDL.Vec(PlayerRanking),
    'uhc' : IDL.Vec(PlayerRanking),
    'diamondSmpNethopSpear' : IDL.Vec(PlayerRanking),
    'mace' : IDL.Vec(PlayerRanking),
    'nethop' : IDL.Vec(PlayerRanking),
    'sword' : IDL.Vec(PlayerRanking),
    'vanilla' : IDL.Vec(PlayerRanking),
    'overall' : IDL.Vec(PlayerRanking),
    'spearMace' : IDL.Vec(PlayerRanking),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func([PlayerRanking], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(PlayerRanking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMaxRankedPoints' : IDL.Func([], [IDL.Nat], ['query']),
    'getPlayer' : IDL.Func([IDL.Text], [IDL.Opt(PlayerRanking)], ['query']),
    'getPlayerRankByRanking' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PlayerRanking)],
        ['query'],
      ),
    'getRankingCategories' : IDL.Func([], [RankingGroup], ['query']),
    'getRankingCategory' : IDL.Func([], [RankingGroup], ['query']),
    'getRankingEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getRawRankingData' : IDL.Func([], [RawRankingData], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPlayersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PlayerRanking)],
        ['query'],
      ),
    'switchRankingCategory' : IDL.Func([RankingGroup], [RankingGroup], []),
  });
};

export const init = ({ IDL }) => { return []; };