/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlayerRanking {
  'region' : string,
  'title' : string,
  'username' : string,
  'badges' : Array<TierCategory>,
  'uuid' : string,
  'rankPosition' : bigint,
  'points' : bigint,
}
export type RankingGroup = string;
export interface RawRankingData {
  'axe' : Array<PlayerRanking>,
  'smp' : Array<PlayerRanking>,
  'uhc' : Array<PlayerRanking>,
  'mace' : Array<PlayerRanking>,
  'nethop' : Array<PlayerRanking>,
  'spear' : Array<PlayerRanking>,
  'sword' : Array<PlayerRanking>,
  'vanilla' : Array<PlayerRanking>,
  'overall' : Array<PlayerRanking>,
  'spearMace' : Array<PlayerRanking>,
  'diamondSmp' : Array<PlayerRanking>,
}
export interface TierCategory { 'tier' : string, 'category' : string }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<[string, PlayerRanking], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPlayers' : ActorMethod<[], Array<PlayerRanking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMaxRankedPoints' : ActorMethod<[], bigint>,
  'getPlayer' : ActorMethod<[string], [] | [PlayerRanking]>,
  'getPlayerRankByRanking' : ActorMethod<[string], [] | [PlayerRanking]>,
  'getPlayersByCategory' : ActorMethod<[string], Array<PlayerRanking>>,
  'getRankingCategories' : ActorMethod<[], RankingGroup>,
  'getRankingCategory' : ActorMethod<[], RankingGroup>,
  'getRankingEntryCount' : ActorMethod<[], bigint>,
  'getRawRankingData' : ActorMethod<[], RawRankingData>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removePlayer' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPlayersByName' : ActorMethod<[string], Array<PlayerRanking>>,
  'switchRankingCategory' : ActorMethod<[RankingGroup], RankingGroup>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];